apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: other
configMapGenerator:
- name: otel-env
  env: config.properties
vars:
- name: ADOT_IAM_ROLE
  objref:
    kind: ConfigMap
    name: otel-env
    apiVersion: v1
  fieldref:
    fieldpath: data.ADOT_IAM_ROLE
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml