apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: rds-ack-options
  envs:
  - rds-ack-options.env
vars:
- name: CATALOG_PASSWORD
  objref:
    kind: ConfigMap
    name: rds-ack-options
    apiVersion: v1
  fieldref:
    fieldpath: data.CATALOG_PASSWORD
configurations:
  - env-var-transformer.yaml
resources:
- rds-secret-reader.yaml
- rds-secret-writer.yaml
- rds-fieldexports-reader.yaml
- rds-fieldexports-writer.yaml
